### ISSUE TITLE
HTML best practices

### ISSUE THREAD

**Issue by Alejandro-Bernal-M** [Alejandro-Bernal-M/To-do-list#6]
add alt and src to img tags

**Comment by EddieJorden** [comment]
hello Alejandro, I have updated the img tags with src properties however unable to push.

getting error
remote: Permission to Alejandro-Bernal-M/To-do-list.git denied to EddieJorden.
fatal: unable to access 'https://github.com/Alejandro-Bernal-M/To-do-list/': The requested URL returned error: 403

**Comment by Alejandro-Bernal-M** [comment]
Hi @EddieJorden this issue was about an exercise on microverse where we need to identify our errors on the HTML best practices  and then compare it when the finds of our partner so that's why you don't the permission to push into my repository
