### ISSUE TITLE
Peer to peer - Code Review

### ISSUE THREAD

**Issue by NicolasAndrehh** [Alejandro-Bernal-M/To-do-list#8]
# Code Review
Hey @Alejandro-Bernal-M, you did a great job but there are some things that can be improved:
- I kindly recommend you use CSS classes to change that background property and then you can just use `Element.Classlist.add('classname')` this way your code will be more readable and easy to understand
https://github.com/Alejandro-Bernal-M/To-do-list/blob/4949196ca7d08dcce1d2a1c2f571ef6cf2741cbc/src/index.js#L29-L30
https://github.com/Alejandro-Bernal-M/To-do-list/blob/4949196ca7d08dcce1d2a1c2f571ef6cf2741cbc/src/index.js#L42-L43

- Good job with your index.js file, but I think it would be better if you put some comments on it, that way your code will be more readable and easier to understand

- I kindly recommend you implement `outline: none` in your inputs for it to improve the UX
- I notice that you have a parenthesis that doesn't do anything, please remove it

**Comment by Alejandro-Bernal-M** [comment]
Thank you for the recommendations, they were all applied.
<img src="https://media2.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif"/>
